apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # These values will be filled by the deploy script from .env
  # The script will automatically encode them to base64
  openai-api-key: "OPENAI_API_KEY_BASE64"
  weaviate-url: "WEAVIATE_URL_BASE64"
  weaviate-api-key: "WEAVIATE_API_KEY_BASE64" 