apiVersion: v1
kind: Service
metadata:
  name: streamlit-app
  labels:
    app: streamlit-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: streamlit-app 